import { useEffect, useRef } from "react";
import type { Point } from "geojson";
import maplibregl, { GeoJSONSource, LngLatBounds } from "maplibre-gl";
import type { PoiCollection, PoiFeature } from "../data/types";

const STYLE="https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json";
const SOURCE="kr-pois",CLUSTERS="clusters",COUNTS="cluster-count",POINTS="points";
function koreanLabels(map:maplibregl.Map){for(const layer of map.getStyle().layers||[]){if(layer.type!=="symbol")continue;const field=layer.layout?.["text-field"];if(!field||!JSON.stringify(field).toLowerCase().includes("name"))continue;try{map.setLayoutProperty(layer.id,"text-field",["coalesce",["get","name_ko"],["get","name:ko"],["get","name"],["get","name_en"]])}catch{}}}
function fit(map:maplibregl.Map,data:PoiCollection){const coordinates=data.features.map(f=>f.geometry.coordinates as [number,number]);if(!coordinates.length)return;if(coordinates.length===1){map.easeTo({center:coordinates[0],zoom:14,duration:300});return}const bounds=new LngLatBounds();coordinates.forEach(c=>bounds.extend(c));if(!bounds.isEmpty())map.fitBounds(bounds,{padding:80,maxZoom:12,duration:400})}
export function PoiMap({data,onSelect}:{data:PoiCollection;onSelect:(f:PoiFeature)=>void}){const container=useRef<HTMLDivElement>(null),mapRef=useRef<maplibregl.Map|null>(null),loaded=useRef(false),latest=useRef(data),select=useRef(onSelect);latest.current=data;select.current=onSelect;
useEffect(()=>{if(!container.current||mapRef.current)return;const map=new maplibregl.Map({container:container.current,style:STYLE,center:[127.7,36.2],zoom:6.2,minZoom:4,attributionControl:{compact:true}});map.addControl(new maplibregl.NavigationControl({showCompass:false}),"top-right");map.addControl(new maplibregl.GeolocateControl({positionOptions:{enableHighAccuracy:true},trackUserLocation:false}),"top-right");map.on("load",()=>{koreanLabels(map);map.addSource(SOURCE,{type:"geojson",data:latest.current,cluster:true,clusterMaxZoom:13,clusterRadius:44});map.addLayer({id:CLUSTERS,type:"circle",source:SOURCE,filter:["has","point_count"],paint:{"circle-color":"#4b62d0","circle-radius":["step",["get","point_count"],13,100,18,1000,23],"circle-opacity":.88,"circle-stroke-color":"#fff","circle-stroke-width":2}});map.addLayer({id:COUNTS,type:"symbol",source:SOURCE,filter:["has","point_count"],layout:{"text-field":["get","point_count_abbreviated"],"text-size":11},paint:{"text-color":"#fff"}});map.addLayer({id:POINTS,type:"circle",source:SOURCE,filter:["!",["has","point_count"]],paint:{"circle-radius":["interpolate",["linear"],["zoom"],6,3.5,14,7],"circle-color":["match",["get","match_status"],"matched","#159070","new_candidate","#e8842a","#7755c8"],"circle-opacity":.92,"circle-stroke-color":"#fff","circle-stroke-width":1.5}});[CLUSTERS,POINTS].forEach(id=>{map.on("mouseenter",id,()=>map.getCanvas().style.cursor="pointer");map.on("mouseleave",id,()=>map.getCanvas().style.cursor="")});map.on("click",CLUSTERS,e=>{const f=e.features?.[0];if(f?.geometry.type==="Point")map.easeTo({center:(f.geometry as Point).coordinates as [number,number],zoom:Math.min(map.getZoom()+2,14),duration:300})});map.on("click",POINTS,e=>{const f=e.features?.[0];if(f?.geometry.type==="Point")select.current(f as PoiFeature)});loaded.current=true;fit(map,latest.current)});mapRef.current=map;return()=>{map.remove();mapRef.current=null;loaded.current=false}},[]);
useEffect(()=>{const map=mapRef.current;if(!map||!loaded.current)return;(map.getSource(SOURCE) as GeoJSONSource|undefined)?.setData(data);fit(map,data)},[data]);return <div className="map" ref={container} aria-label="한국 POI 지도"/>}

