import { useEffect,useMemo,useState } from "react";
import { AdSlot } from "./components/AdSlot";import { DetailPanel } from "./components/DetailPanel";import { Downloads } from "./components/Downloads";import { Filters } from "./components/Filters";import { loadPortalData } from "./data/loadData";import type { Metadata,PoiCollection,PoiFeature } from "./data/types";import { PoiMap } from "./map/PoiMap";
const empty:PoiCollection={type:"FeatureCollection",features:[]};const value=(v:unknown)=>v==null?"":String(v);const unique=(v:string[])=>[...new Set(v.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"ko"));
export default function App(){const [collection,setCollection]=useState(empty),[metadata,setMetadata]=useState<Metadata|null>(null),[selected,setSelected]=useState<PoiFeature|null>(null),[query,setQuery]=useState(""),[brand,setBrand]=useState(""),[spider,setSpider]=useState(""),[status,setStatus]=useState(""),[panel,setPanel]=useState<"filters"|"downloads"|"about"|null>(null),[error,setError]=useState("");
useEffect(()=>{loadPortalData().then(({collection,metadata})=>{setCollection(collection);setMetadata(metadata)}).catch(reason=>setError(reason instanceof Error?reason.message:String(reason)))},[]);
const options=useMemo(()=>({brands:unique(collection.features.map(f=>value(f.properties?.brand))),spiders:unique(collection.features.map(f=>value(f.properties?.["@spider"]))),statuses:unique(collection.features.map(f=>value(f.properties?.match_status)))}),[collection]);
const filtered=useMemo<PoiCollection>(()=>{const needle=query.trim().toLocaleLowerCase("ko");return {...collection,features:collection.features.filter(f=>{const p=f.properties||{};const hay=[p.name,p.branch,p.brand,p["addr:full"],p["@spider"],p.ref].map(value).join(" ").toLocaleLowerCase("ko");return(!needle||hay.includes(needle))&&(!brand||value(p.brand)===brand)&&(!spider||value(p["@spider"])===spider)&&(!status||value(p.match_status)===status)})}},[collection,query,brand,spider,status]);
const reset=()=>{setQuery("");setBrand("");setSpider("");setStatus("")};const active=Boolean(query||brand||spider||status);const date=metadata?new Date(metadata.generated_at).toLocaleDateString("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit"}):"불러오는 중";
return <div className="app"><header className="topbar"><div className="identity"><a className="org" href="https://gisdev-kr.github.io">GISDEV-KR</a><span className="slash">/</span><a className="title" href={import.meta.env.BASE_URL}>ALL THE PLACES KR</a></div><nav><button onClick={()=>setPanel(panel==="about"?null:"about")}>소개</button><a href="https://github.com/gisdev-kr/alltheplaces-kr">GitHub ↗</a></nav></header><main className="stage">{!error&&<PoiMap data={filtered} onSelect={setSelected}/>}<section className="dataset-card"><div className="dataset-title"><span className="mark"><i/><i/><i/></span><div><h1>All the Places <b>KR</b></h1><p>공식 ATP 한국 spider 월간 스냅샷</p></div></div><div className="dataset-stats"><span><b>{collection.features.length.toLocaleString("ko-KR")}</b> POI</span><span><b>{metadata?.spider_count??"—"}</b> spiders</span><span><b>{date}</b> generated</span></div></section><label className="search"><span>⌕</span><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="장소, 브랜드, 주소 검색" aria-label="POI 검색"/>{query&&<button onClick={()=>setQuery("")} aria-label="검색어 지우기">×</button>}</label><div className="toolbar"><button className={panel==="filters"||active?"active":""} onClick={()=>setPanel(panel==="filters"?null:"filters")}>필터 {active&&<i/>}</button><button className={panel==="downloads"?"active":""} onClick={()=>setPanel(panel==="downloads"?null:"downloads")}>다운로드</button></div>
{panel==="filters"&&<section className="floating filters-panel"><header><strong>표시할 POI</strong><button onClick={()=>setPanel(null)}>×</button></header><Filters {...options} brand={brand} spider={spider} status={status} onBrand={setBrand} onSpider={setSpider} onStatus={setStatus}/><button className="reset" onClick={reset} disabled={!active}>필터 초기화</button></section>}{panel==="downloads"&&<section className="floating downloads-panel"><header><strong>월간 데이터</strong><button onClick={()=>setPanel(null)}>×</button></header><p>필터와 무관한 전체 최신 스냅샷입니다.</p><Downloads/></section>}{panel==="about"&&<section className="floating about-panel"><header><strong>이 지도에 관하여</strong><button onClick={()=>setPanel(null)}>×</button></header><p>공식 All the Places 코드는 Git submodule로 사용하며 한국 전용 spider만 실행합니다. OSM 파일은 검토용이며 자동 업로드되지 않습니다.</p><a href="https://gisdev-kr.github.io/blog/">개발 기록 읽기 →</a></section>}
<div className="legend"><span><i className="review"/>검토 필요</span><span><i className="matched"/>OSM 매치</span><span><i className="candidate"/>신규 후보</span></div><div className="count"><b>{filtered.features.length.toLocaleString("ko-KR")}</b>개 표시 중 {active&&<button onClick={reset}>전체 보기</button>}</div>{selected&&<DetailPanel feature={selected} onClose={()=>setSelected(null)}/>} {!metadata&&!error&&<div className="message">POI 데이터를 불러오는 중입니다…</div>}{error&&<div className="message error"><strong>데이터를 불러오지 못했습니다.</strong><span>{error}</span></div>}<AdSlot/></main></div>}

